### ISSUE TITLE
Nota TP N° 3

### ISSUE THREAD

**Issue by caroapaza** [Alexis-Correjidor/repo-tp2#41]
Grupo 15, les dejo la nota del Trabajo Práctico N° 3: 10 (diez)

En el repositorio hay un usuario con nombre Buscapina que no se logra identificar a que alumno pertenece.
Solo se ven commits de Castellón, Correjidor y Vilte.
Los alumnos Héctor Alejandro Chosco y Omar Ninaja siguen perteneciendo al grupo?

Saludos.

**Comment by Alexis-Correjidor** [comment]
Buenas Noches Profe, si en nuestro grupo15 solo quedamos tres integrantes,
el resto abandonaron.

1-Castellon Agustín Miqueas, Usuario en github: AgustinCastellon
2- Vilte Ezequiel Carlos, Usuario en github: ecvilte
3-Correjidor Alexis Gabriel, Usuario en github: Alexis-Correjidor

Y por la corrección que nos hace sobre el usuario como "buscapina" es
Agustín Castellon, en el Network si uno se acentúa sobre el nodo es decir
la fusión de su rama a la rama principal main si figura su nombre pero
cuando nos paramos sobre solo su rama creada figura un alias de
"buscapina", alias que intento modificar desde el github pero no cambiaba a
pesar de haber puesto su nombre y apellido en lo que creemos eran los
campos correspondientes(a partir de ese momento figuraba su nombre en
fusión de su rama con main pero no cuando se acentuaban sobre solo su
rama), por lo que otro compañero aconsejo hacerlo desde el spring acción
que ya realizó, espero se vean reflejado los cambios.

Además de responder por este medio también acabo de subir al aula virtual
los integrantes que seguimos.

**Comment by caroapaza** [comment]
> 

Buenas noches. Ya actualicé la lista del grupo.
Saludos.
